#!/bin/bash
rm meter.csv
for ship in $(cat shipsIMO.txt)
do
bash FindShipDistance "$ship" >>meter.csv
done
a=$(cat meter.csv|cut -d "," -f 2|sort -gr|head -n 1)
b=$(grep $a meter.csv|cut -d "," -f 1)
echo "$b,$a"
