#!/bin/bash
rm tmpship.csv
id=$(grep -i "$1" shipsNAME-IMO.txt|cut -d "," -f 2) 
cp 'PerShip/'$id'.csv' tmpship.csv
vs=$(octave -q ShipDistance.m 2>/dev/null)
id=$(grep -i "$1" shipsNAME-IMO.txt|cut -d "," -f 2|cut -d "O" -f 2)
echo "$id,$vs"
